CREATE TABLE volunteer_applications (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    age INTEGER,
    location TEXT,
    availability_weekdays BOOLEAN DEFAULT false,
    availability_weekends BOOLEAN DEFAULT false,
    availability_mornings BOOLEAN DEFAULT false,
    availability_afternoons BOOLEAN DEFAULT false,
    availability_evenings BOOLEAN DEFAULT false,
    skills TEXT,
    experience_animals TEXT,
    experience_farming TEXT,
    motivation_cs TEXT,
    motivation_en TEXT,
    preferred_activities JSONB,
    emergency_contact_name VARCHAR(100),
    emergency_contact_phone VARCHAR(20),
    has_drivers_license BOOLEAN DEFAULT false,
    can_lift_heavy BOOLEAN DEFAULT false,
    allergies TEXT,
    medical_conditions TEXT,
    preferred_language VARCHAR(5) DEFAULT 'cs',
    status VARCHAR(20) DEFAULT 'pending',
    notes TEXT,
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    reviewed_by VARCHAR(100)
);